services:
  frontend:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISPLAY: ${DISPLAY}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    image: careagain/careagain-webapp:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    dns:
      - 1.1.1.1
    command: reflex run --frontend-only --loglevel debug
    depends_on:
      - app
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISPLAY: ${DISPLAY}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    image: careagain/careagain-webapp:latest
    env_file:
      - .env
    ports:
      - 8000:8000
    dns:
      - 1.1.1.1
    command: reflex run --env prod --backend-only --loglevel debug
