"""empty message

Revision ID: ea402340af0a
Revises: 
Create Date: 2025-05-15 16:11:08.481747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea402340af0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dev_careagain_projects_project_id', table_name='projects', schema='dev_careagain')
    op.drop_table('projects', schema='dev_careagain')
    op.drop_index('ix_dev_careagain_users_projects_rel_up_id', table_name='users_projects', schema='dev_careagain')
    op.drop_table('users_projects', schema='dev_careagain')
    op.drop_index('ix_dev_careagain_users_user_id', table_name='users', schema='dev_careagain')
    op.drop_table('users', schema='dev_careagain')
    op.drop_index('ix_dev_careagain_videos_video_id', table_name='videos', schema='dev_careagain')
    op.drop_table('videos', schema='dev_careagain')
    op.drop_index('ix_dev_careagain_questions_question_id', table_name='questions', schema='dev_careagain')
    op.drop_table('questions', schema='dev_careagain')
    op.drop_index('ix_dev_careagain_users_orgs_rel_uo_id', table_name='users_orgs', schema='dev_careagain')
    op.drop_table('users_orgs', schema='dev_careagain')
    op.drop_index('ix_dev_careagain_organizations_org_id', table_name='organizations', schema='dev_careagain')
    op.drop_table('organizations', schema='dev_careagain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('activation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('storage_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('org_id', name='organizations_pkey'),
    schema='dev_careagain',
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_dev_careagain_organizations_org_id', 'organizations', ['org_id'], unique=False, schema='dev_careagain')
    op.create_table('users_orgs',
    sa.Column('rel_uo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('member_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['dev_careagain.organizations.org_id'], name='users_orgs_org_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['dev_careagain.users.user_id'], name='users_orgs_user_id_fkey'),
    sa.PrimaryKeyConstraint('rel_uo_id', name='users_orgs_pkey'),
    schema='dev_careagain'
    )
    op.create_index('ix_dev_careagain_users_orgs_rel_uo_id', 'users_orgs', ['rel_uo_id'], unique=False, schema='dev_careagain')
    op.create_table('questions',
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('question', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['dev_careagain.users.user_id'], name='questions_created_by_fkey'),
    sa.PrimaryKeyConstraint('question_id', name='questions_pkey'),
    schema='dev_careagain'
    )
    op.create_index('ix_dev_careagain_questions_question_id', 'questions', ['question_id'], unique=False, schema='dev_careagain')
    op.create_table('videos',
    sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('youtube_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['dev_careagain.users.user_id'], name='videos_created_by_fkey'),
    sa.PrimaryKeyConstraint('video_id', name='videos_pkey'),
    schema='dev_careagain'
    )
    op.create_index('ix_dev_careagain_videos_video_id', 'videos', ['video_id'], unique=False, schema='dev_careagain')
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deactivation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='dev_careagain',
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_dev_careagain_users_user_id', 'users', ['user_id'], unique=False, schema='dev_careagain')
    op.create_table('users_projects',
    sa.Column('rel_up_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('member_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dev_careagain.users.user_id'], name='users_projects_user_id_fkey'),
    sa.PrimaryKeyConstraint('rel_up_id', name='users_projects_pkey'),
    schema='dev_careagain'
    )
    op.create_index('ix_dev_careagain_users_projects_rel_up_id', 'users_projects', ['rel_up_id'], unique=False, schema='dev_careagain')
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('repo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('guide', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('project_id', name='projects_pkey'),
    schema='dev_careagain'
    )
    op.create_index('ix_dev_careagain_projects_project_id', 'projects', ['project_id'], unique=False, schema='dev_careagain')
    # ### end Alembic commands ###
