name: Build and Push Container

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "docker-compose.yaml"
      - "requirements.txt"
      - assets/
      - webapp/
      - rxconfig.py
      - alembic.ini
      - alembic/
      - .github/workflows/build.yaml

env:
  # DOCKER_IMAGE: careagain/webapp
  # uncomment if using
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_REPO }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # For Reflex to build a container,
      # injecting your environment variables at
      # container build time is often required.
      - name: Create build env file
        run: |
          cat << EOF > .build-env
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_DB_SCHEMA=${{ secrets.SUPABASE_DB_SCHEMA}}
          SUPABASE_DB_URI=${{ secrets.SUPABASE_DB_URI }}
          SUPABASE_S3_ACCESS_KEY_ID=${{ secrets.SUPABASE_S3_ACCESS_KEY_ID}}
          SUPABASE_S3_BUCKET=${{ secrets.SUPABASE_S3_BUCKET}}
          SUPABASE_S3_SECRET_ACCESS_KEY=${{ secrets.SUPABASE_S3_SECRET_ACCESS_KEY}}
          SUPABASE_URL=${{ secrets.SUPABASE_URL}}
          API_URL=${{ secrets.API_URL}}
          WEB_URL=${{ secrets.WEB_URL }}
          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
          BACKEND_PORT=${{ secrets.BACKEND_PORT }}
          EOF

      - name: Build and push Docker image for linux/arm64
        run: |
          docker buildx build \
            --dns=1.1.1.1 \
            --platform linux/arm64 \
            -f Dockerfile \
            -t ${{ env.DOCKER_IMAGE }}:latest \
            -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
            --push .

      - name: Remove build env file
        run: rm .build-env
