"""empty message

Revision ID: ac4f8682bd44
Revises: 
Create Date: 2024-09-27 00:17:42.590809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ac4f8682bd44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_organizations_org_id')

    op.drop_table('organizations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_project_id')

    op.drop_table('projects')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_question_id')

    op.drop_table('questions')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('ix_videos_video_id')

    op.drop_table('videos')
    with op.batch_alter_table('users_projects', schema=None) as batch_op:
        batch_op.drop_index('ix_users_projects_rel_up_id')

    op.drop_table('users_projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('ix_users_user_id')

    op.drop_table('users')
    with op.batch_alter_table('users_orgs', schema=None) as batch_op:
        batch_op.drop_index('ix_users_orgs_rel_uo_id')

    op.drop_table('users_orgs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_orgs',
    sa.Column('rel_uo_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member_type', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name='users_orgs_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='users_orgs_ibfk_1'),
    sa.PrimaryKeyConstraint('rel_uo_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users_orgs', schema=None) as batch_op:
        batch_op.create_index('ix_users_orgs_rel_uo_id', ['rel_uo_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activation_date', sa.DATE(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('deactivation_date', sa.DATE(), nullable=True),
    sa.Column('storage_path', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_user_id', ['user_id'], unique=False)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('users_projects',
    sa.Column('rel_up_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member_type', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='users_projects_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='users_projects_ibfk_1'),
    sa.PrimaryKeyConstraint('rel_up_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users_projects', schema=None) as batch_op:
        batch_op.create_index('ix_users_projects_rel_up_id', ['rel_up_id'], unique=False)

    op.create_table('videos',
    sa.Column('video_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('youtube_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='videos_ibfk_1'),
    sa.PrimaryKeyConstraint('video_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index('ix_videos_video_id', ['video_id'], unique=False)

    op.create_table('questions',
    sa.Column('question_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('question', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='questions_ibfk_1'),
    sa.PrimaryKeyConstraint('question_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_question_id', ['question_id'], unique=False)

    op.create_table('projects',
    sa.Column('project_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_project_id', ['project_id'], unique=False)

    op.create_table('organizations',
    sa.Column('org_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('org_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activation_date', sa.DATE(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('storage_path', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('org_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('ix_organizations_org_id', ['org_id'], unique=False)

    # ### end Alembic commands ###
